// examples/simple/Comment.svelte
<script>
  export let comment;
  $: ({ author, text, time: timestamp } = comment);
  let clickCounter = 0;
  let nameState = 'Old Name';
</script>

<div class="comment">
  <div class="comment-metadata">{author} · {timestamp}</div>

  <div>{nameState}</div>
  <button onClick={() => (nameState = 'New Name')}>
    Click here to change name
  </button>

  <div class="comment-body">
    {@html text}
  </div>

  <button on:click={() => (clickCounter += 1)}>Click here</button>
</div>

// examples/simple/Comment.jsx
import React, { useState } from 'react';

export default ({ comment }) => {
  const { author, text, time: timestamp } = comment;

  const [clickCounter, setclickCounter] = useState(0);
  const nameState = useState('Old Name');

  return (
    <div className="comment">
      <div className="comment-metadata">
        {author} · {timestamp}
      </div>

      <div>{nameState[0]}</div>
      <button onClick={() => nameState[1]('New Name')}>
        Click here to change name
      </button>

      <div
        className="comment-body"
        dangerouslySetInnerHTML={{ __html: text }}
      ></div>

      <button onClick={() => setclickCounter(clickCounter + 1)}>
        Click here to increase count
      </button>
    </div>
  );
};
